version: 2
jobs:
  build:
    docker:
      - image:
        cmd: ["/bin/bash"]
        ports:
          - "3000:3000"
      - image: browserless/chrome
        ports:
          - "3000:3000"
    environment:
      APP_NAME: design
      GCLOUD_PROJECT:
      GCLOUD_CLUSTER:
      NAMESPACE:
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc;
            yarn install --pure-lockfile
      - run:
          name: Running visual regression tests
          command: |
            yarn vr-test
